version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - pscs-network
  processo-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: processo_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308:3308
    networks:
      - pscs-network
  naming-server:
    image: phelippnd/naming-server:latest
    ports:
      - 8761:8761
    networks:
      - pscs-network
  gateway-server:
    image: phelippnd/gateway-server:latest
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
    networks:
      - pscs-network
  processo-service:
    image: phelippnd/processo-service:latest
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - processo-db
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.DATASOURCE.URL: jdbc:mysql://processo-db:3308/processo_service?useSSL=false&serverTimezono=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2
    networks:
      - pscs-network
volumes:
  db:
    driver: local
networks:
  pscs-network:
    driver: bridge