version: '3.4'

services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - pscs-network    
  zipkin:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://quest:quest@rabbit-mq:5672
    networks:
      - pscs-network
  processo-db: 
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: processo_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - pscs-network
  naming-server:
    image: phelippnd/naming-server:latest
    restart: always
    ports:
      - 8761:8761
    networks:
      - pscs-network
  api-gateway:
    image: phelippnd/api-gateway:latest
    restart: always
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      RABBIT_URI: amqp://quest:quest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq

    networks:
      - pscs-network
  processo-service:
    image: phelippnd/processo-service:latest
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - processo-db
      - rabbit-mq
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.DATASOURCE.URL: jdbc:mysql://processo-db:3308/processo_service?useSSL=false&serverTimezono=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      RABBIT_URI: amqp://quest:quest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
    networks:
      - pscs-network
volumes:
  db:
    driver: local
networks:
  pscs-network:
    driver: bridge